language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-composer' ]; then cd .. && eval "mv $currentfolder generator-composer" && cd generator-composer; fi

